# Generated by Django 5.1.2 on 2024-10-15 11:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0002_ridesattraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticket_type', models.CharField(choices=[('Day Pass', 'Day Pass'), ('Limited Pass', 'Limited Pass')], max_length=50)),
                ('number_of_rides', models.PositiveIntegerField(default=0)),
                ('date_reservation', models.DateField(default=django.utils.timezone.now)),
                ('receipt_of_payment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
