# Generated by Django 5.1.2 on 2024-10-17 05:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0004_delete_ticketreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('day_pass_date', models.DateField(blank=True, null=True)),
                ('regular_pass_quantity', models.PositiveIntegerField(default=0)),
                ('junior_pass_quantity', models.PositiveIntegerField(default=0)),
                ('pwd_senior_pass_quantity', models.PositiveIntegerField(default=0)),
                ('limited_pass_date', models.DateField(blank=True, null=True)),
                ('roller_coaster_quantity', models.PositiveIntegerField(default=0)),
                ('jungle_splash_quantity', models.PositiveIntegerField(default=0)),
                ('surf_dance_quantity', models.PositiveIntegerField(default=0)),
                ('frisbee_quantity', models.PositiveIntegerField(default=0)),
                ('viking_quantity', models.PositiveIntegerField(default=0)),
                ('meow_meow_quantity', models.PositiveIntegerField(default=0)),
                ('frosty_train_quantity', models.PositiveIntegerField(default=0)),
                ('kiddie_wheel_quantity', models.PositiveIntegerField(default=0)),
                ('mini_pirate_quantity', models.PositiveIntegerField(default=0)),
                ('kids_playland_quantity', models.PositiveIntegerField(default=0)),
                ('music_express_quantity', models.PositiveIntegerField(default=0)),
                ('bump_car_quantity', models.PositiveIntegerField(default=0)),
                ('ferris_wheel_quantity', models.PositiveIntegerField(default=0)),
                ('carousel_quantity', models.PositiveIntegerField(default=0)),
                ('fun_swing_quantity', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acknowledgementReceipt.customuser')),
            ],
        ),
    ]
