# Generated by Django 5.1.2 on 2024-10-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0005_ticketreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketReservation',
        ),
    ]
