# Generated by Django 5.1.2 on 2024-10-17 05:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0006_delete_ticketreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ticket_types', models.CharField(max_length=100)),
                ('number_of_rides', models.PositiveIntegerField()),
                ('date_reservation', models.DateField(default=django.utils.timezone.now)),
                ('receipt_of_payment', models.FileField(upload_to='receipts/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acknowledgementReceipt.customuser', to_field='email')),
            ],
        ),
    ]
