# Generated by Django 5.1.2 on 2024-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0008_delete_ticketreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('regular_quantity', models.PositiveIntegerField(default=0)),
                ('junior_quantity', models.PositiveIntegerField(default=0)),
                ('pwd_senior_quantity', models.PositiveIntegerField(default=0)),
                ('roller_coaster_quantity', models.PositiveIntegerField(default=0)),
                ('jungle_splash_quantity', models.PositiveIntegerField(default=0)),
                ('surf_dance_quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_purchase', models.DateTimeField()),
            ],
        ),
    ]
