# Generated by Django 5.1.2 on 2024-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0009_ticketreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreservation',
            name='jungle_splash_quantity',
        ),
        migrations.RemoveField(
            model_name='ticketreservation',
            name='junior_quantity',
        ),
        migrations.RemoveField(
            model_name='ticketreservation',
            name='pwd_senior_quantity',
        ),
        migrations.RemoveField(
            model_name='ticketreservation',
            name='roller_coaster_quantity',
        ),
        migrations.RemoveField(
            model_name='ticketreservation',
            name='surf_dance_quantity',
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='limited_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='number_of_rides',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
