# Generated by Django 5.1.2 on 2024-10-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0010_remove_ticketreservation_jungle_splash_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreservation',
            old_name='regular_quantity',
            new_name='unlimited_quantity',
        ),
    ]
