# Generated by Django 5.1.2 on 2024-10-19 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0011_rename_regular_quantity_ticketreservation_unlimited_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, unique=True)),
                ('lastname', models.CharField(max_length=150, unique=True)),
                ('emailadd', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
