# Generated by Django 5.1.2 on 2024-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0013_gate_adminaccount_delete_gateadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='receipt_of_payment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
