# Generated by Django 5.1.2 on 2024-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0015_ridesattraction_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidesAttraction_Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='archive_attractions/')),
                ('archived_description', models.TextField()),
                ('archived_information', models.TextField()),
            ],
        ),
    ]
