# Generated by Django 5.1.2 on 2024-11-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0016_ridesattraction_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation_Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name_archive', models.CharField(max_length=150)),
                ('customer_email_archive', models.EmailField(max_length=254)),
                ('unlimited_quantity_archive', models.PositiveIntegerField(default=0)),
                ('limited_quantity_archive', models.PositiveIntegerField(default=0)),
                ('number_of_rides_archive', models.PositiveIntegerField(default=0)),
                ('receipt_of_payment_archive', models.PositiveIntegerField(default=0)),
                ('total_price_archive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_purchase_archive', models.DateTimeField()),
            ],
        ),
    ]
