# Generated by Django 5.0.6 on 2024-11-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0017_ticketreservation_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesattraction',
            name='category',
            field=models.CharField(choices=[('attractions', 'Attractions'), ('kiddie', 'Kiddie Rides'), ('extreme', 'Extreme Rides')], default='attractions', max_length=50),
        ),
    ]
