# Generated by Django 5.0.6 on 2024-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0018_ridesattraction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesattraction',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
