# Generated by Django 5.1.2 on 2024-11-29 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0019_alter_ridesattraction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAAdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DECLINED', 'Declined')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ridesattraction',
            name='category',
            field=models.CharField(choices=[('attractions', 'Attractions'), ('kiddie', 'Kiddie Rides'), ('family', 'Family Rides'), ('extreme', 'Extreme Rides')], default='attractions', max_length=50),
        ),
    ]
