# Generated by Django 5.1.2 on 2025-01-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledgementReceipt', '0022_remove_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='ticket_date_availed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
